INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Buy Books", "School Supplies", 1000, "2017-01-01", "2017-09-01");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Procure Luggage", "Travel Items", 500, "2017-01-01", "2017-06-01");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Get Tickets", "Travel", 2000, "2017-01-01", "2017-04-15");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Pay for Term 1", "Tuition", 30000, "2015-01-01", "2017-07-15");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Pay for Term 2", "Tuition", 30000, "2015-01-01", "2018-01-15");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Pay for Term 3", "Tuition", 30000, "2016-01-01", "2018-07-15");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Pay for Term 4", "Tuition", 30000, "2016-01-01", "2019-01-15");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Pay for Term 5", "Tuition", 30000, "2017-01-01", "2019-07-15");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Pay for Term 6", "Tuition", 30000, "2017-01-01", "2020-01-01");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Buy Computer", "School Supplies",4000, "2016-05-01", "2017-07-15");

INSERT INTO users (name, age) VALUES ("Mom", 59);
INSERT INTO users (name, age) VALUES ("Aunt Linda", 61);
INSERT INTO users (name, age) VALUES ("Uncle Orrie", 75);
INSERT INTO users (name, age) VALUES ("Tricia", 26);
INSERT INTO users (name, age) VALUES ("Christine", 28);
INSERT INTO users (name, age) VALUES ("Sam", 18);
INSERT INTO users (name, age) VALUES ("Grandpa", 93);
INSERT INTO users (name, age) VALUES ("Peter", 18);
INSERT INTO users (name, age) VALUES ("Max", 17);
INSERT INTO users (name, age) VALUES ("Jake", 18);
INSERT INTO users (name, age) VALUES ("Chad", 18);
INSERT INTO users (name, age) VALUES ("Margaret", 54);
INSERT INTO users (name, age) VALUES ("Kate", 56);
INSERT INTO users (name, age) VALUES ("Helen", 55);
INSERT INTO users (name, age) VALUES ("Joe", 57);
INSERT INTO users (name, age) VALUES ("Maddy", 18);
INSERT INTO users (name, age) VALUES ("Uncle Andrew", 55);
INSERT INTO users (name, age) VALUES ("Aunt Ann", 55);
INSERT INTO users (name, age) VALUES ("Beckie", 28);
INSERT INTO users (name, age) VALUES ("Ellie", 24);


INSERT INTO pledges (amount, user_id, project_id) VALUES (25000,1,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25000,1,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30000,1,6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000,7,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000,6,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20000,1,8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000,6,9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20000,1,9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000,2,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1500,18,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,3,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,9,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50,8,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,2,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000,4,10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000,20,10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1500,14,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200,19,8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (250,5,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000,6,9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000,17,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,12,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (750,15,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (250,18,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,16,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75,13,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25,11,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30,10,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000,6,8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (7500,7,9);
