insert into series values (1, 1, 1, 'Harry Potter');
insert into series values (2, 2, 2, 'Enders Game');
insert into subgenres values (1, "Fantasy");
insert into subgenres values (2, "Science Fiction");
insert into authors values (1, "JK Rowling");
insert into authors values (2, "Orson Scott Card");
insert into books values (1, "Harry Potter and Sorcerer's Stone", 1993, 1);
insert into books values (2, "Harry Potter and Chamber of Secrets", 1995, 1);
insert into books values (3, "Harry Potter and Prisoner of Ahzkaban", 1997, 1);
insert into books values (4, "Ender's Game", 1984, 2);
insert into books values (5, "Speaker for the Dead ", 1985, 2);
insert into books values (6, "Ender's Shadow ", 1987, 2);
insert into characters values(1, "Harry Potter", "human", "yes", 1, 1);
insert into characters values(2, "Ron Weasley", "human", "no", 1, 1);
insert into characters values(3, "Hermione Grander", "human", "neither", 1, 1);
insert into characters values(4, "Dobby", "house elf", "harry potter is great", 1, 1);
insert into characters values(5, "Ender", "human", "live", 2, 2);
insert into characters values(6, "Bean", "human", "live more", 2, 2);
insert into characters values(7, "Buggers", "Alien", "die", 2, 2);
insert into characters values(8, "Valentine", "human", "friendly", 2, 2);
insert into character_books values (1,1,1);
insert into character_books values (2,2,1);
insert into character_books values (3,3,1);
insert into character_books values (4,4,1);
insert into character_books values (5,1,2);
insert into character_books values (6,2,2);
insert into character_books values (7,3,2);
insert into character_books values (8,4,2);
insert into character_books values (9,1,3);
insert into character_books values (10,2,4);
insert into character_books values (11,4,5);
insert into character_books values (12,5,6);
insert into character_books values (13,6,7);
insert into character_books values (14,4,8);
insert into character_books values (15,5,5);
insert into character_books values (16,6,6);

