INSERT INTO series (title,author_id, subgenre_id) VALUES ("Harry Potter", 1, 1);
INSERT INTO series (title,author_id, subgenre_id) VALUES ("The Hunger Games", 2, 2);
INSERT INTO subgenres (name) VALUES ("fantasy");
INSERT INTO subgenres (name) VALUES ("science fiction");
INSERT INTO authors (name) VALUES ("J.K. Rowling");
INSERT INTO authors (name) VALUES ("Suzanne Collins");
INSERT INTO books (title, year, series_id) VALUES ("Harry Potter and the Sorcerer's Stone", 1997, 1);
INSERT INTO books (title, year, series_id) VALUES ("Harry Potter and the Chamber of Secrets", 1998, 1);
INSERT INTO books (title, year, series_id) VALUES ("Harry Potter and the Goblet of Fire", 2000, 1);
INSERT INTO books (title, year, series_id) VALUES ("The Hunger Games", 2008, 2);
INSERT INTO books (title, year, series_id) VALUES ("Catching Fire", 2009, 2);
INSERT INTO books (title, year, series_id) VALUES ("Mockingjay", 2010, 2);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Harry Potter", "Dudley sucks", "wizard", 1, 1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Hermione Granger", "Wingardium leviosa", "wizard", 1, 1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Professor Quirrell", "Pppppppleased to meet you Harry", "wizard", 1, 1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Viktor Krum", "I lost", "wizard", 1, 1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Katniss Everdeen", "Girl on fire", "human", 2, 2);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Haymitch Abernathy", "Give me a drink", "human", 2, 2);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Finnick Odair", "Do you want a sugar cube?", "human", 2, 2);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("President Alma Coin", "I'm evil", "human", 2, 2);
INSERT INTO character_books (character_id, book_id) VALUES (1, 1);
INSERT INTO character_books (character_id, book_id) VALUES (1, 2);
INSERT INTO character_books (character_id, book_id) VALUES (1, 3);
INSERT INTO character_books (character_id, book_id) VALUES (2, 1);
INSERT INTO character_books (character_id, book_id) VALUES (2, 2);
INSERT INTO character_books (character_id, book_id) VALUES (2, 3);
INSERT INTO character_books (character_id, book_id) VALUES (3, 1);
INSERT INTO character_books (character_id, book_id) VALUES (4, 3);
INSERT INTO character_books (character_id, book_id) VALUES (5, 4);
INSERT INTO character_books (character_id, book_id) VALUES (5, 5);
INSERT INTO character_books (character_id, book_id) VALUES (5, 6);
INSERT INTO character_books (character_id, book_id) VALUES (6, 4);
INSERT INTO character_books (character_id, book_id) VALUES (6, 5);
INSERT INTO character_books (character_id, book_id) VALUES (6, 6);
INSERT INTO character_books (character_id, book_id) VALUES (7, 4);
INSERT INTO character_books (character_id, book_id) VALUES (8, 6);