#has 2 series (FAILED - 18)
  #has 6 books (FAILED - 19)
  #has 8 characters (FAILED - 20)
  #has 2 subgenres (FAILED - 21)
  #has 2 authors (FAILED - 22)
  has 16 joins in character_books (FAILED - 23)
